### ISSUE TITLE
Missing Identity environment variables

### ISSUE THREAD

**Issue by jwulf** [camunda/camunda-docs#3446]
The following variables can be used to configure M2M clients and tenants in Identity, and are not documented here https://docs.camunda.io/docs/self-managed/identity/deployment/configuration-variables/#feature-flags:
```
      IDENTITY_TENANTS_0_NAME: Default
      IDENTITY_TENANTS_0_TENANTID: <default>
      IDENTITY_TENANTS_0_MEMBERS_0_TYPE: APPLICATION
      IDENTITY_TENANTS_0_MEMBERS_0_APPLICATIONID: zeebe
      IDENTITY_ENVIRONMENT_TENANTS_0_NAME: Default
      IDENTITY_ENVIRONMENT_TENANTS_0_TENANTID: <default>
      KEYCLOAK_CLIENTS_0_NAME: zeebe
      KEYCLOAK_CLIENTS_0_ID: ${ZEEBE_CLIENT_ID}
      KEYCLOAK_CLIENTS_0_SECRET: ${ZEEBE_CLIENT_SECRET}
      KEYCLOAK_CLIENTS_0_TYPE: M2M
      KEYCLOAK_CLIENTS_0_PERMISSIONS_0_RESOURCE_SERVER_ID: zeebe-api
      KEYCLOAK_CLIENTS_0_PERMISSIONS_0_DEFINITION: write:*
      KEYCLOAK_CLIENTS_0_PERMISSIONS_1_RESOURCE_SERVER_ID: operate-api
      KEYCLOAK_CLIENTS_0_PERMISSIONS_1_DEFINITION: write:*
      KEYCLOAK_CLIENTS_0_PERMISSIONS_2_RESOURCE_SERVER_ID: tasklist-api
      KEYCLOAK_CLIENTS_0_PERMISSIONS_2_DEFINITION: write:*
      KEYCLOAK_CLIENTS_0_PERMISSIONS_3_RESOURCE_SERVER_ID: optimize-api
      KEYCLOAK_CLIENTS_0_PERMISSIONS_3_DEFINITION: write:*
      KEYCLOAK_CLIENTS_0_PERMISSIONS_4_RESOURCE_SERVER_ID: tasklist-api
      KEYCLOAK_CLIENTS_0_PERMISSIONS_4_DEFINITION: read:*
      KEYCLOAK_CLIENTS_0_PERMISSIONS_5_RESOURCE_SERVER_ID: operate-api
      KEYCLOAK_CLIENTS_0_PERMISSIONS_5_DEFINITION: read:*
```

**Comment by akeller** [comment]
Follow up on internal Slack - https://camunda.slack.com/archives/CRQAL5A1M/p1710189093137139

**Comment by nloding** [comment]
Adding a note: we should also include how to configure this via the application.yaml, like so:
```
  tenants:
    - name: Identity Team
      tenantId: identity-team
      members:
        - type: GROUP
          group-name: "Test Group"
        - type: USER
          username: my-demo-user
        - type: APPLICATION
          application-id: test-application
 ```
 
This should be true for all of the configuration values across all applications. Can it be configured via environment variable, application.yaml, and/or Helm, and what are those values with examples and defaults?
