### ISSUE TITLE
Undocumented shards/replicas configuration for Elasticsearch Exporter

### ISSUE THREAD

**Issue by falko** [camunda/camunda-docs#3745]
According to the configuration file there are properties for configuring sharding and replicas:
https://github.com/camunda/zeebe/blob/42cc7744e88ad4aac655f115a8a270f0556e6432/dist/src/main/config/broker.yaml.template#L665-L666

But they are not shown in the documentation:
https://github.com/camunda/camunda-docs/blob/a644fe5c72a56e94409b13b65fb5733a3dd75a84/docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md?plain=1#L74-L78

And their behavior is not explained anywhere.

**Comment by falko** [comment]
@daniel-ewing pointed out that the name of the corresponding environment variables may be hard to guess:

```yaml
zeebe: 
  env: 
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_NUMBEROFSHARDS
      value: "1"
```

~ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_NUMBER_OF_SHARDS~ does not work.
