### ISSUE TITLE
Update needed on Ingress configuration in Camunda 8 Helm charts

### ISSUE THREAD

**Issue by cdonuut** [camunda/camunda-docs#3926]
Hi Docs team,

At a client call we realized that our documentation should be updated to reflect the correct indentation required to have a successful setup. 

This is the documentation: https://github.com/camunda/camunda-docs/blob/main/docs/self-managed/setup/deploy/local/local-kubernetes-cluster.md

As you can see, at the current state Ingress is in the same root level as global. Ingress should be 1 level inside the global value. See corrected version below: 

```
global:
  ingress:
    enabled: true
    className: nginx
    host: "camunda.local"
  
  operate:
    contextPath: "/operate"
  
  tasklist:
    contextPath: "/tasklist"
  
  zeebeGateway:
    ingress:
      enabled: true
      className: nginx
      host: "zeebe.camunda.local"
```
      
      
 If you have any question please let us know.
 
 Cheers,
 Donat
