### ISSUE TITLE
reintroduce caching in CI builds

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#4418]
In #4417, we removed the `docuactions/cache` action from our preview-env-deploy.yaml workflow, because the organization left GitHub. 

We should reintroduce caching into _all_ of our CI build workflows, based instead on local code. 

I tracked what I _think_ is a fork to https://github.com/tats-u/docuactions-cache/blob/main/action.yml. The contents look pretty straightforward, I'm capturing here in case they eventually disappear too:

```
name: "Docusaurus Cache"
description: "Cache Docusaurus for faster application rebuilds."
author: "docuactions"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/.docusaurus
          ${{ github.workspace }}/**/.cache
        key: |
          ${{ runner.os }}-docusaurus-${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-docusaurus-${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}
branding:
  icon: "archive"
  color: "green"
```

The cached paths align with [the recommendations in the Docusaurus discord](https://discord.com/channels/398180168688074762/867060369087922187/1224717527687630911), so even if this isn't a fork of the original action, it is a worthy source.
