### ISSUE TITLE
Spring getting started guide provides incomplete configuration for c8run

### ISSUE THREAD

**Issue by meyerdan** [camunda/camunda-docs#4911]
The spring getting started guide provides incomplete client configuration to connect to c8run.
c8run has ssl disabled and this must be set in the client configuration accordingly.

This is the client / SDK configuration provided:

```
camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      grpc-address: http://127.0.0.1:26500
      rest-address: http://127.0.0.1:8080
```

This is the line that is missing:

```
zeebe.client.security.plaintext= true
```
