### ISSUE TITLE
Add Debug logging config to the Connectors doc

### ISSUE THREAD

**Issue by zalanszak** [camunda/camunda-docs#5165]
Add to docs how to configure log level for connectors:
```

connectors:
  env:
    - name: LOGGING_LEVEL_IO_CAMUNDA_CONNECTOR
      value: DEBUG
```

**Comment by akeller** [comment]
@zalanszak, this looks like a quick fix. Would you expect to see this info https://docs.camunda.io/docs/next/self-managed/connectors-deployment/connectors-configuration/#logging?

**Comment by akeller** [comment]
We should also add a link [here](https://docs.camunda.io/docs/next/self-managed/operational-guides/troubleshooting/log-levels/), so long as the log levels for Connectors follow the same log levels.

@sbuettner, when I was quickly triaging this, I see other components include more info than just turning it on (see [Operate](https://docs.camunda.io/docs/next/self-managed/operate-deployment/operate-configuration/#logging) or [Optimize](https://docs.camunda.io/optimize/next/self-managed/optimize-deployment/configuration/logging/)). 

How should we add this for [Connectors](https://docs.camunda.io/docs/next/self-managed/connectors-deployment/connectors-configuration/#logging)?

**Comment by jasueh** [comment]
Adding my two cents here.

The following should be set to get the full outbound and inbound details (such as request and response headers) for the REST Connector. 

```
connectors:
  env:
    - name: LOGGING_LEVEL_ORG_APACHE_HC_CLIENT5
      value: DEBUG
```

I've only tested it with the REST Connector; I don't know if other connectors use the same HTTP Client for the requests. 
And, of course, this is only configurable for Self-Manage.
